### ISSUE TITLE
Simplified docker-compose

### ISSUE THREAD

**Issue by codywarmbo** [dogbin/server#10]
Amazing project! I truly love it. The persistent URL is a major boon in my opinion. However, is the `docker-compose.yml` a little overloaded at the moment? Is there a slim version one might try to just get this up and running quick without  so many containers?

Thanks!

**Comment by codywarmbo** [comment]
I quickly found something as simple as this works just fine to try things out quickly.

```
---
version: "3"
services:
  dogbin:
    image: dogbin/dogbin
    restart: unless-stopped
    environment:
      - DB_LOCATION=/dogbin.xdb
      - HOST=0.0.0.0
    volumes:
      - ./dogbin.xdb:/dogbin.xdb
    ports:
      - 83:8080
```
